//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSchoolModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolClass
    {
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> GradeId { get; set; }
    }
}
