//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSchoolModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int SId { get; set; }
        public string SName { get; set; }
        public string SSex { get; set; }
        public Nullable<System.DateTime> SBornDate { get; set; }
        public Nullable<int> SAge { get; set; }
        public string SCardNumber { get; set; }
        public Nullable<int> SGrade { get; set; }
        public string SPhone { get; set; }
        public Nullable<int> SEducational { get; set; }
        public string SAddress { get; set; }
        public string SPolitical { get; set; }
        public Nullable<int> SClass { get; set; }
        public string SPicture { get; set; }
        public Nullable<System.DateTime> SEntrance { get; set; }
        public Nullable<int> SDormitories { get; set; }
        public string SQQNumber { get; set; }
        public Nullable<int> SCurriculum { get; set; }
        public string SRemark { get; set; }
    }
}
